from dataclasses import dataclass
from enum import Enum


class Granularity(Enum):
    # Outline: Only skeleton of the node (series of headings, for example)
    OUTLINE = "outline"

    # Subtree: Content of the node and everything below it. May be good for mid-level questions
    # Can produce big text
    SUBTREE = "subtree"

    # Own text: content a node owns, for any node
    OWN_TEXT = "own_text"

    # Summary generated by AI usually.
    SUMMARY = "summary"




@dataclass(frozen=True)
class Chunk:
    text: str
    logical_document_id: str

    # Context - usually the sections that make sense of the chunk text
    # Can be empty (e.g., for top-level nodes)
    context: str
    
    # Node on which the chunk is derived
    node_id: str
    # The node's pre-order index
    node_position: int
    # Level corresponding the node's level, defined as in the profile
    node_level: str

    # chunking_strategy, applied on the chunk
    chunking_strategy: str

    # granularity: what kind of chunk this is (from the chunker)
    granularity: Granularity

    @property
    def id(self) -> str:
        return f"{self.logical_document_id}::{self.chunking_strategy}::{self.node_id}::{self.granularity.value}"

    def __post_init__(self) -> None:
        if not self.text.strip():
            raise ValueError("chunk text cannot be empty")
        
        if (not self.node_id) or (not self.logical_document_id):
            raise ValueError("orphaned chunk: node_id and logical_document_id cannot be empty")
        
        if not self.node_level:
            raise ValueError("chunk level cannot be empty")
        
        if not self.chunking_strategy:
            raise ValueError("chunking_strategy cannot be empty")
        
        if self.node_position < 0:
            raise ValueError("chunk level cannot be negative")





